export const courtsList = [
    "1ª Unidade do Núcleo 4.0 - Previdenciário || 92801",
    "1ª Vara da Comarca de Coari - Criminal || 20001",
    "1ª Vara da Comarca de Coari - Cível || 20101",
    "1ª Vara da Comarca de Coari - Execução Penal || 50401",
    "1ª Vara da Comarca de Coari - Família || 20201",
    "1ª Vara da Comarca de Coari - Infância e Juventude Cível || 20301",
    "1ª Vara da Comarca de Coari - Infância e Juventude Infracional || 20401",
    "1ª Vara da Comarca de Coari - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 77001",
    "1ª Vara da Comarca de Coari - Registros Públicos || 53201",
    "1ª Vara da Comarca de Humaitá - Criminal || 237",
    "1ª Vara da Comarca de Humaitá - Cível || 337",
    "1ª Vara da Comarca de Humaitá - Execução Penal || 50001",
    "1ª Vara da Comarca de Humaitá - Família || 437",
    "1ª Vara da Comarca de Humaitá - Infância e Juventude Cível || 537",
    "1ª Vara da Comarca de Humaitá - Infância e Juventude Infracional || 637",
    "1ª Vara da Comarca de Humaitá - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 75901",
    "1ª Vara da Comarca de Humaitá - Procedimentos Administrativos || 58601",
    "1ª Vara da Comarca de Humaitá - Registros Públicos || 1237",
    "1ª Vara da Comarca de Iranduba - Criminal || 4901",
    "1ª Vara da Comarca de Iranduba - Cível || 5001",
    "1ª Vara da Comarca de Iranduba - Execução Penal || 49601",
    "1ª Vara da Comarca de Iranduba - Família || 5101",
    "1ª Vara da Comarca de Iranduba - Infância e Juventude Cível || 5201",
    "1ª Vara da Comarca de Iranduba - Infância e Juventude Infracional || 5301",
    "1ª Vara da Comarca de Iranduba - JE Criminal || 5401",
    "1ª Vara da Comarca de Iranduba - JE Cível || 5501",
    "1ª Vara da Comarca de Iranduba - Procedimentos Administrativos || 52601",
    "1ª Vara da Comarca de Iranduba - Registros Públicos || 52701",
    "1ª Vara da Comarca de Itacoatiara - Criminal || 1501",
    "1ª Vara da Comarca de Itacoatiara - Cível || 1601",
    "1ª Vara da Comarca de Itacoatiara - Execução Penal || 48601",
    "1ª Vara da Comarca de Itacoatiara - Família || 1701",
    "1ª Vara da Comarca de Itacoatiara - Infância e Juventude Cível || 1801",
    "1ª Vara da Comarca de Itacoatiara - Infância e Juventude Infracional || 1901",
    "1ª Vara da Comarca de Itacoatiara - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 80201",
    "1ª Vara da Comarca de Manacapuru - Criminal || 9801",
    "1ª Vara da Comarca de Manacapuru - Cível || 9901",
    "1ª Vara da Comarca de Manacapuru - Execução Penal || 47901",
    "1ª Vara da Comarca de Manacapuru - Família || 10001",
    "1ª Vara da Comarca de Manacapuru - Infância e Juventude Cível || 10101",
    "1ª Vara da Comarca de Manacapuru - Infância e Juventude Infracional || 10201",
    "1ª Vara da Comarca de Manacapuru - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 82301",
    "1ª Vara da Comarca de Manacapuru - Registros Públicos || 52901",
    "1ª Vara da Comarca de Manicoré - Criminal || 238",
    "1ª Vara da Comarca de Manicoré - Cível || 338",
    "1ª Vara da Comarca de Manicoré - Execução Penal || 49201",
    "1ª Vara da Comarca de Manicoré - Família || 638",
    "1ª Vara da Comarca de Manicoré - Infância e Juventude Cível || 838",
    "1ª Vara da Comarca de Manicoré - Infância e Juventude Infracional || 1038",
    "1ª Vara da Comarca de Manicoré - JE Criminal || 1238",
    "1ª Vara da Comarca de Manicoré - JE Cível || 1438",
    "1ª Vara da Comarca de Manicoré - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 78301",
    "1ª Vara da Comarca de Manicoré - Registros Públicos || 53501",
    "1ª Vara da Comarca de Maués - Criminal || 15401",
    "1ª Vara da Comarca de Maués - Cível || 15601",
    "1ª Vara da Comarca de Maués - Execução Penal || 46101",
    "1ª Vara da Comarca de Maués - Família || 15801",
    "1ª Vara da Comarca de Maués - Infância e Juventude Cível || 16001",
    "1ª Vara da Comarca de Maués - Infância e Juventude Infracional || 16201",
    "1ª Vara da Comarca de Maués - JE Criminal || 16401",
    "1ª Vara da Comarca de Maués - JE Cível || 16501",
    "1ª Vara da Comarca de Maués - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 79001",
    "1ª Vara da Comarca de Maués - Registros Públicos || 53101",
    "1ª Vara da Comarca de Parintins - Criminal || 22801",
    "1ª Vara da Comarca de Parintins - Cível || 22901",
    "1ª Vara da Comarca de Parintins - Execução Penal || 45401",
    "1ª Vara da Comarca de Parintins - Família || 23001",
    "1ª Vara da Comarca de Parintins - Infância e Juventude Cível || 23101",
    "1ª Vara da Comarca de Parintins - Infância e Juventude Infracional || 23201",
    "1ª Vara da Comarca de Parintins - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 79401",
    "1ª Vara da Comarca de Tabatinga - Criminal || 13301",
    "1ª Vara da Comarca de Tabatinga - Cível || 13501",
    "1ª Vara da Comarca de Tabatinga - Execução Penal || 45001",
    "1ª Vara da Comarca de Tabatinga - Família || 13601",
    "1ª Vara da Comarca de Tabatinga - Infância e Juventude Cível || 13701",
    "1ª Vara da Comarca de Tabatinga - Infância e Juventude Infracional || 13901",
    "1ª Vara da Comarca de Tabatinga - JE Criminal || 14001",
    "1ª Vara da Comarca de Tabatinga - JE Cível || 14101",
    "1ª Vara da Comarca de Tabatinga - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 81801",
    "1ª Vara da Comarca de Tabatinga - Registros Públicos || 53001",
    "1ª Vara da Comarca de Tefé - Criminal || 307",
    "1ª Vara da Comarca de Tefé - Cível || 16801",
    "1ª Vara da Comarca de Tefé - Execução Penal || 44201",
    "1ª Vara da Comarca de Tefé - Família || 107",
    "1ª Vara da Comarca de Tefé - Infância e Juventude Cível || 507",
    "1ª Vara da Comarca de Tefé - Infância e Juventude Infracional || 707",
    "1ª Vara da Comarca de Tefé - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 81101",
    "1ª Vara da Comarca de Tefé - Registros Públicos || 53401",
    "1ª Vara da Comarca de xxx - Criminal || 32901",
    "1ª Vara da Comarca de xxx - Família || 33201",
    "1ª Vara da Comarca de xxx - Infância e Juventude Cível || 33001",
    "1ª Vara da Comarca de xxx - Infância e Juventude Infracional || 33101",
    "1º Juizado Especial da Comarca de Coari - JE Cível || 20601",
    "1º Juizado Especial da Comarca de Humaitá - JE Cível || 21301",
    "1º Juizado Especial da Comarca de Humaitá - Procedimentos Administrativos || 58801",
    "1º Juizado Especial da Comarca de Itacoatiara - JE Cível || 2101",
    "1º Juizado Especial da Comarca de Manacapuru - JE Cível || 10401",
    "1º Juizado Especial da Comarca de Parintins - JE Cível || 24401",
    "1º Juizado Especial da Comarca de Tefé - JE Cível || 17001",
    "2ª Unidade do Núcleo 4.0 - Previdenciário || 92901",
    "2ª Vara da Comarca de Coari - Criminal || 20701",
    "2ª Vara da Comarca de Coari - Cível || 20801",
    "2ª Vara da Comarca de Coari - Execução Penal || 50501",
    "2ª Vara da Comarca de Coari - Família || 20901",
    "2ª Vara da Comarca de Coari - Infância e Juventude Cível || 21001",
    "2ª Vara da Comarca de Coari - Infância e Juventude Infracional || 21101",
    "2ª Vara da Comarca de Coari - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 76201",
    "2ª Vara da Comarca de Humaitá - Criminal || 737",
    "2ª Vara da Comarca de Humaitá - Cível || 837",
    "2ª Vara da Comarca de Humaitá - Execução Penal || 50101",
    "2ª Vara da Comarca de Humaitá - Família || 937",
    "2ª Vara da Comarca de Humaitá - Infância e Juventude Cível || 1037",
    "2ª Vara da Comarca de Humaitá - Infância e Juventude Infracional || 1137",
    "2ª Vara da Comarca de Humaitá - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 76901",
    "2ª Vara da Comarca de Humaitá - Procedimentos Administrativos || 58701",
    "2ª Vara da Comarca de Iranduba - Criminal || 5601",
    "2ª Vara da Comarca de Iranduba - Cível || 5701",
    "2ª Vara da Comarca de Iranduba - Execução Penal || 49701",
    "2ª Vara da Comarca de Iranduba - Família || 5801",
    "2ª Vara da Comarca de Iranduba - Infância e Juventude Cível || 5901",
    "2ª Vara da Comarca de Iranduba - Infância e Juventude Infracional || 6001",
    "2ª Vara da Comarca de Iranduba - JE Criminal || 6101",
    "2ª Vara da Comarca de Iranduba - JE Cível || 6201",
    "2ª Vara da Comarca de Itacoatiara - Criminal || 2201",
    "2ª Vara da Comarca de Itacoatiara - Cível || 2301",
    "2ª Vara da Comarca de Itacoatiara - Execução Penal || 48701",
    "2ª Vara da Comarca de Itacoatiara - Família || 2401",
    "2ª Vara da Comarca de Itacoatiara - Infância e Juventude Cível || 2501",
    "2ª Vara da Comarca de Itacoatiara - Infância e Juventude Infracional || 2601",
    "2ª Vara da Comarca de Itacoatiara - JE Criminal || 2701",
    "2ª Vara da Comarca de Itacoatiara - JE Cível || 2801",
    "2ª Vara da Comarca de Itacoatiara - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 77601",
    "2ª Vara da Comarca de Manacapuru - Criminal || 10501",
    "2ª Vara da Comarca de Manacapuru - Cível || 10601",
    "2ª Vara da Comarca de Manacapuru - Execução Penal || 48001",
    "2ª Vara da Comarca de Manacapuru - Família || 10701",
    "2ª Vara da Comarca de Manacapuru - Infância e Juventude Cível || 10801",
    "2ª Vara da Comarca de Manacapuru - Infância e Juventude Infracional || 10901",
    "2ª Vara da Comarca de Manacapuru - JE Criminal || 11001",
    "2ª Vara da Comarca de Manacapuru - JE Cível || 11101",
    "2ª Vara da Comarca de Manacapuru - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 79301",
    "2ª Vara da Comarca de Manicoré - Criminal || 538",
    "2ª Vara da Comarca de Manicoré - Cível || 438",
    "2ª Vara da Comarca de Manicoré - Execução Penal || 49301",
    "2ª Vara da Comarca de Manicoré - Família || 738",
    "2ª Vara da Comarca de Manicoré - Infância e Juventude Cível || 938",
    "2ª Vara da Comarca de Manicoré - Infância e Juventude Infracional || 1138",
    "2ª Vara da Comarca de Manicoré - JE Criminal || 1338",
    "2ª Vara da Comarca de Manicoré - JE Cível || 1538",
    "2ª Vara da Comarca de Manicoré - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 78001",
    "2ª Vara da Comarca de Maués - Criminal || 15501",
    "2ª Vara da Comarca de Maués - Cível || 15701",
    "2ª Vara da Comarca de Maués - Execução Penal || 46201",
    "2ª Vara da Comarca de Maués - Família || 15901",
    "2ª Vara da Comarca de Maués - Infância e Juventude Cível || 16101",
    "2ª Vara da Comarca de Maués - Infância e Juventude Infracional || 16301",
    "2ª Vara da Comarca de Maués - JE Criminal || 16601",
    "2ª Vara da Comarca de Maués - JE Cível || 16701",
    "2ª Vara da Comarca de Maués - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 77401",
    "2ª Vara da Comarca de Parintins - Criminal || 23301",
    "2ª Vara da Comarca de Parintins - Cível || 23401",
    "2ª Vara da Comarca de Parintins - Execução Penal || 45501",
    "2ª Vara da Comarca de Parintins - Família || 23501",
    "2ª Vara da Comarca de Parintins - Infância e Juventude Cível || 23601",
    "2ª Vara da Comarca de Parintins - Infância e Juventude Infracional || 23701",
    "2ª Vara da Comarca de Parintins - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 82101",
    "2ª Vara da Comarca de Tabatinga - Criminal || 13401",
    "2ª Vara da Comarca de Tabatinga - Cível || 13801",
    "2ª Vara da Comarca de Tabatinga - Execução Penal || 45101",
    "2ª Vara da Comarca de Tabatinga - Família || 14201",
    "2ª Vara da Comarca de Tabatinga - Infância e Juventude Cível || 14301",
    "2ª Vara da Comarca de Tabatinga - Infância e Juventude Infracional || 14401",
    "2ª Vara da Comarca de Tabatinga - JE Criminal || 14501",
    "2ª Vara da Comarca de Tabatinga - JE Cível || 14601",
    "2ª Vara da Comarca de Tabatinga - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 82401",
    "2ª Vara da Comarca de Tefé - Criminal || 407",
    "2ª Vara da Comarca de Tefé - Cível || 16901",
    "2ª Vara da Comarca de Tefé - Execução Penal || 44501",
    "2ª Vara da Comarca de Tefé - Família || 207",
    "2ª Vara da Comarca de Tefé - Infância e Juventude Cível || 607",
    "2ª Vara da Comarca de Tefé - Infância e Juventude Infracional || 807",
    "2ª Vara da Comarca de Tefé - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 79901",
    "2ª Vara da Comarca de xxx - Criminal || 33301",
    "2ª Vara da Comarca de xxx - Família || 33401",
    "2ª Vara da Comarca de xxx - Infância e Juventude Cível || 33501",
    "2ª Vara da Comarca de xxx - Infância e Juventude Infracional || 33601",
    "3ª Unidade do Núcleo 4.0 - Previdenciário || 93001",
    "3ª Vara da Comarca de Itacoatiara - Criminal || 2901",
    "3ª Vara da Comarca de Itacoatiara - Cível || 3001",
    "3ª Vara da Comarca de Itacoatiara - Execução Penal || 48801",
    "3ª Vara da Comarca de Itacoatiara - Família || 3101",
    "3ª Vara da Comarca de Itacoatiara - Infância e Juventude Cível || 3201",
    "3ª Vara da Comarca de Itacoatiara - Infância e Juventude Infracional || 3301",
    "3ª Vara da Comarca de Itacoatiara - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 78801",
    "3ª Vara da Comarca de Itacoatiara - Registros Públicos || 52801",
    "3ª Vara da Comarca de Parintins - Criminal || 23801",
    "3ª Vara da Comarca de Parintins - Cível || 23901",
    "3ª Vara da Comarca de Parintins - Execução Penal || 45601",
    "3ª Vara da Comarca de Parintins - Família || 24001",
    "3ª Vara da Comarca de Parintins - Infância e Juventude Cível || 24101",
    "3ª Vara da Comarca de Parintins - Infância e Juventude Infracional || 24201",
    "3ª Vara da Comarca de Parintins - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 77801",
    "3ª Vara da Comarca de Parintins - Registros Públicos || 53301",
    "CEJUSC Lábrea - Pré-Processual Cível || 75701",
    "CEJUSC Lábrea - Pré-Processual JE Cível || 75501",
    "Central de Inquéritos Policiais da Comarca de Alvarães - Inquéritos Policiais || 63201",
    "Central de Inquéritos Policiais da Comarca de Boa Vista do Ramos - Inquéritos Policiais || 62701",
    "Central de Inquéritos Policiais da Comarca de Careiro da Várzea - Inquéritos Policiais || 60001",
    "Central de Inquéritos Policiais da Comarca de Envira - Inquéritos Policiais || 59401",
    "Central de Inquéritos Policiais da Comarca de Nova Olinda do Norte - Inquéritos Policiais || 61901",
    "Central de Inquéritos Policiais da Comarca de Novo Airão - Inquéritos Policiais || 59301",
    "Central de Inquéritos Policiais da Comarca de Novo Aripuanã - Inquéritos Policiais || 61701",
    "Central de Inquéritos Policiais da Comarca de Rio Preto da Eva - Inquéritos Policiais || 60801",
    "Central de Inquéritos Policiais da Comarca de Silves - Inquéritos Policiais || 60101",
    "Central de Inquéritos Policiais da Comarca de São Paulo de Olivença - Inquéritos Policiais || 61101",
    "Polo 1: Vara de Plantão da Comarca de Amaturá - Criminal || 84301",
    "Polo 1: Vara de Plantão da Comarca de Amaturá - Cível || 88601",
    "Polo 1: Vara de Plantão da Comarca de Atalaia do Norte - Criminal || 83801",
    "Polo 1: Vara de Plantão da Comarca de Atalaia do Norte - Cível || 88501",
    "Polo 1: Vara de Plantão da Comarca de Barcelos - Criminal || 83701",
    "Polo 1: Vara de Plantão da Comarca de Barcelos - Cível || 87901",
    "Polo 1: Vara de Plantão da Comarca de Benjamin Constant - Criminal || 74701",
    "Polo 1: Vara de Plantão da Comarca de Benjamin constant - Cível || 88001",
    "Polo 1: Vara de Plantão da Comarca de Santa Isabel do Rio Negro - Criminal || 84001",
    "Polo 1: Vara de Plantão da Comarca de Santa Isabel do Rio Negro - Cível || 88201",
    "Polo 1: Vara de Plantão da Comarca de Santo Antonio do Iça - Cível || 88301",
    "Polo 1: Vara de Plantão da Comarca de Santo Antonio do Içá - Criminal || 84101",
    "Polo 1: Vara de Plantão da Comarca de São Gabriel Da Cachoeira - Criminal || 83901",
    "Polo 1: Vara de Plantão da Comarca de São Gabriel da Cachoeira - Cível || 88101",
    "Polo 1: Vara de Plantão da Comarca de São Paulo de Olivença - Criminal || 84201",
    "Polo 1: Vara de Plantão da Comarca de São Paulo de Olivença - Cível || 88401",
    "Polo 1: Vara de Plantão da Comarca de Tabatinga - Criminal || 65101",
    "Polo 1: Vara de Plantão da Comarca de Tabatinga - Cível || 65601",
    "Polo 2: Vara de Plantão da Comarca de Alvarães - Criminal || 84501",
    "Polo 2: Vara de Plantão da Comarca de Alvarães - Cível || 89401",
    "Polo 2: Vara de Plantão da Comarca de Fonte Boa - Criminal || 84701",
    "Polo 2: Vara de Plantão da Comarca de Fonte Boa - Cível || 88901",
    "Polo 2: Vara de Plantão da Comarca de Japurá - Criminal || 84601",
    "Polo 2: Vara de Plantão da Comarca de Japurá - Cível || 88801",
    "Polo 2: Vara de Plantão da Comarca de Juruá - Criminal || 84901",
    "Polo 2: Vara de Plantão da Comarca de Juruá - Cível || 89301",
    "Polo 2: Vara de Plantão da Comarca de Jutaí - Criminal || 84801",
    "Polo 2: Vara de Plantão da Comarca de Jutaí - Cível || 89001",
    "Polo 2: Vara de Plantão da Comarca de Maraã - Criminal || 85001",
    "Polo 2: Vara de Plantão da Comarca de Maraã - Cível || 89201",
    "Polo 2: Vara de Plantão da Comarca de Tefé - Criminal || 64801",
    "Polo 2: Vara de Plantão da Comarca de Tefé - Cível || 88701",
    "Polo 2: Vara de Plantão da Comarca de Uarini - Criminal || 84401",
    "Polo 2: Vara de Plantão da Comarca de Uarini - Cível || 89101",
    "Polo 3: Vara de Plantão da Comarca de Boca do Acre - Criminal || 85601",
    "Polo 3: Vara de Plantão da Comarca de Boca do Acre - Cível || 90001",
    "Polo 3: Vara de Plantão da Comarca de Canutama - Criminal || 85401",
    "Polo 3: Vara de Plantão da Comarca de Canutama - Cível || 89801",
    "Polo 3: Vara de Plantão da Comarca de Carauari - Criminal || 85201",
    "Polo 3: Vara de Plantão da Comarca de Carauari - Cível || 89601",
    "Polo 3: Vara de Plantão da Comarca de Eirunepé - Criminal || 85101",
    "Polo 3: Vara de Plantão da Comarca de Eirunepé - Cível || 89501",
    "Polo 3: Vara de Plantão da Comarca de Envira - Criminal || 75001",
    "Polo 3: Vara de Plantão da Comarca de Envira - Cível || 74901",
    "Polo 3: Vara de Plantão da Comarca de Guajará - Criminal || 83401",
    "Polo 3: Vara de Plantão da Comarca de Guajará - Cível || 83301",
    "Polo 3: Vara de Plantão da Comarca de Ipixuna - Criminal || 83101",
    "Polo 3: Vara de Plantão da Comarca de Ipixuna - Cível || 83201",
    "Polo 3: Vara de Plantão da Comarca de Itamarati - Criminal || 75301",
    "Polo 3: Vara de Plantão da Comarca de Itamarati - Cível || 75401",
    "Polo 3: Vara de Plantão da Comarca de Lábrea - Criminal || 85301",
    "Polo 3: Vara de Plantão da Comarca de Lábrea - Cível || 89701",
    "Polo 3: Vara de Plantão da Comarca de Pauini - Criminal || 85501",
    "Polo 3: Vara de Plantão da Comarca de Pauini - Cível || 89901",
    "Polo 4: Vara de Plantão da Comarca de Apuí - Criminal || 85801",
    "Polo 4: Vara de Plantão da Comarca de Apuí - Cível || 90201",
    "Polo 4: Vara de Plantão da Comarca de Autazes - Criminal || 85701",
    "Polo 4: Vara de Plantão da Comarca de Autazes - Cível || 90101",
    "Polo 4: Vara de Plantão da Comarca de Borba - Criminal || 86101",
    "Polo 4: Vara de Plantão da Comarca de Borba - Cível || 90501",
    "Polo 4: Vara de Plantão da Comarca de Humaitá - Criminal || 82901",
    "Polo 4: Vara de Plantão da Comarca de Humaitá - Cível || 83001",
    "Polo 4: Vara de Plantão da Comarca de Manicoré - Criminal || 85901",
    "Polo 4: Vara de Plantão da Comarca de Manicoré - Cível || 90301",
    "Polo 4: Vara de Plantão da Comarca de Novo Aripuanã - Criminal || 86001",
    "Polo 4: Vara de Plantão da Comarca de Novo Aripuanã - Cível || 90401",
    "Polo 5: Vara de Plantão da Comarca de Caapiranga - Criminal || 74801",
    "Polo 5: Vara de Plantão da Comarca de Caapiranga - Cível || 90701",
    "Polo 5: Vara de Plantão da Comarca de Manacaupuru - Criminal || 65001",
    "Polo 5: Vara de Plantão da Comarca de Manacaupuru - Cível || 65901",
    "Polo 5: Vara de Plantão da Comarca de Novo Airão - Criminal || 86201",
    "Polo 5: Vara de Plantão da Comarca de Novo Airão - Cível || 90601",
    "Polo 6: Vara de Plantão da Comarca de Anamã - Criminal || 74601",
    "Polo 6: Vara de Plantão da Comarca de Anamã - Cível || 91001",
    "Polo 6: Vara de Plantão da Comarca de Anori - Criminal || 86401",
    "Polo 6: Vara de Plantão da Comarca de Anori - Cível || 90901",
    "Polo 6: Vara de Plantão da Comarca de Beruri - Criminal || 86301",
    "Polo 6: Vara de Plantão da Comarca de Beruri - Cível || 90801",
    "Polo 6: Vara de Plantão da Comarca de Coari - Criminal || 74401",
    "Polo 6: Vara de Plantão da Comarca de Coari - Cível || 74301",
    "Polo 6: Vara de Plantão da Comarca de Codajás - Criminal || 86501",
    "Polo 6: Vara de Plantão da Comarca de Codajás - Cível || 91101",
    "Polo 6: Vara de Plantão da Comarca de Tapauá - Criminal || 86601",
    "Polo 6: Vara de Plantão da Comarca de Tapauá - Cível || 91201",
    "Polo 7: Vara de Plantão da Comarca de Careiro Castanho - Criminal || 86801",
    "Polo 7: Vara de Plantão da Comarca de Careiro Castanho - Cível || 91401",
    "Polo 7: Vara de Plantão da Comarca de Careiro da Várzea - Criminal || 86901",
    "Polo 7: Vara de Plantão da Comarca de Careiro da Várzea - Cível || 91501",
    "Polo 7: Vara de Plantão da Comarca de Manaquiri - Criminal || 75101",
    "Polo 7: Vara de Plantão da Comarca de Manaquiri - Cível || 75201",
    "Polo 7: Vara de Plantão da Comarca de Nova Olinda do Norte - Criminal || 87101",
    "Polo 7: Vara de Plantão da Comarca de Nova Olinda do Norte - Cível || 91801",
    "Polo 7: Vara de Plantão da Comarca de Presidente Figueiredo - Criminal || 86701",
    "Polo 7: Vara de Plantão da Comarca de Presidente Figueiredo - Cível || 91301",
    "Polo 7: Vara de Plantão da Comarca de Rio Preto Da Eva - Criminal || 87201",
    "Polo 7: Vara de Plantão da Comarca de Rio Preto da Eva - Cível || 91601",
    "Polo 7: Vara de Plantão da Comarca de Urucurituba - Criminal || 87001",
    "Polo 7: Vara de Plantão da Comarca de Urucurituba - Cível || 91701",
    "Polo 8: Vara de Plantão da Comarca de Itacoatiara - Criminal || 65701",
    "Polo 8: Vara de Plantão da Comarca de Itacoatiara - Cível || 65801",
    "Polo 8: Vara de Plantão da Comarca de Itapiranga - Criminal || 87401",
    "Polo 8: Vara de Plantão da Comarca de Itapiranga - Cível || 92001",
    "Polo 8: Vara de Plantão da Comarca de Maués - Criminal || 64901",
    "Polo 8: Vara de Plantão da Comarca de Maués - Cível || 74501",
    "Polo 8: Vara de Plantão da Comarca de Silves - Criminal || 87301",
    "Polo 8: Vara de Plantão da Comarca de Silves - Cível || 91901",
    "Polo 9: Vara de Plantão da Comarca de Barreirinha - Criminal || 83501",
    "Polo 9: Vara de Plantão da Comarca de Barreirinha - Cível || 83601",
    "Polo 9: Vara de Plantão da Comarca de Boa Vista do Ramos - Criminal || 87801",
    "Polo 9: Vara de Plantão da Comarca de Boa Vista do Ramos - Cível || 92401",
    "Polo 9: Vara de Plantão da Comarca de Nhamundá - Criminal || 87501",
    "Polo 9: Vara de Plantão da Comarca de Nhamundá - Cível || 92101",
    "Polo 9: Vara de Plantão da Comarca de Parintins - Criminal || 65301",
    "Polo 9: Vara de Plantão da Comarca de Parintins - Cível || 65401",
    "Polo 9: Vara de Plantão da Comarca de São Sebastião do Uatumã - Criminal || 87701",
    "Polo 9: Vara de Plantão da Comarca de São Sebastião do Uatumã - Cível || 92301",
    "Polo 9: Vara de Plantão da Comarca de Urucará - Criminal || 87601",
    "Polo 9: Vara de Plantão da Comarca de Urucará - Cível || 92201",
    "Secretaria do Mutirão Carcerário - Comarca de Alvarães || 36701",
    "Secretaria do Mutirão Carcerário - Comarca de Boa Vista do Ramos || 39901",
    "Secretaria do Mutirão Carcerário - Comarca de Careiro da Várzea || 47001",
    "Secretaria do Mutirão Carcerário - Comarca de Envira || 45701",
    "Secretaria do Mutirão Carcerário - Comarca de Nova Olinda do Norte || 42001",
    "Secretaria do Mutirão Carcerário - Comarca de Novo Airão || 41801",
    "Secretaria do Mutirão Carcerário - Comarca de Novo Aripuanã || 41501",
    "Secretaria do Mutirão Carcerário - Comarca de Rio Preto da Eva || 41001",
    "Secretaria do Mutirão Carcerário - Comarca de Silves || 39401",
    "Secretaria do Mutirão Carcerário - Comarca de São Paulo de Olivença || 40201",
    "Vara de Plantão da Comarca de Parintins - Plantão Família || 65501",
    "Vara Única da Comarca de Alvarães - Criminal || 17201",
    "Vara Única da Comarca de Alvarães - Cível || 17301",
    "Vara Única da Comarca de Alvarães - Execução Penal || 36601",
    "Vara Única da Comarca de Alvarães - Família || 17401",
    "Vara Única da Comarca de Alvarães - Infância e Juventude Cível || 17501",
    "Vara Única da Comarca de Alvarães - Infância e Juventude Infracional || 17601",
    "Vara Única da Comarca de Alvarães - JE Criminal || 17701",
    "Vara Única da Comarca de Alvarães - JE Cível || 17801",
    "Vara Única da Comarca de Alvarães - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 76301",
    "Vara Única da Comarca de Alvarães - Registros Públicos || 57901",
    "Vara Única da Comarca de Amaturá - Criminal || 50901",
    "Vara Única da Comarca de Amaturá - Cível || 51001",
    "Vara Única da Comarca de Amaturá - Execução Penal || 52401",
    "Vara Única da Comarca de Amaturá - Família || 51101",
    "Vara Única da Comarca de Amaturá - Infância e Juventude Cível || 51201",
    "Vara Única da Comarca de Amaturá - Infância e Juventude Infracional || 51301",
    "Vara Única da Comarca de Amaturá - JE Criminal || 51401",
    "Vara Única da Comarca de Amaturá - JE Cível || 51501",
    "Vara Única da Comarca de Amaturá - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 76501",
    "Vara Única da Comarca de Amaturá - Registros Públicos || 54201",
    "Vara Única da Comarca de Anamã - Criminal || 31501",
    "Vara Única da Comarca de Anamã - Cível || 31601",
    "Vara Única da Comarca de Anamã - Execução Penal || 36801",
    "Vara Única da Comarca de Anamã - Família || 31701",
    "Vara Única da Comarca de Anamã - Infância e Juventude Cível || 31801",
    "Vara Única da Comarca de Anamã - Infância e Juventude Infracional || 31901",
    "Vara Única da Comarca de Anamã - JE Criminal || 32001",
    "Vara Única da Comarca de Anamã - JE Cível || 32101",
    "Vara Única da Comarca de Anamã - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 76601",
    "Vara Única da Comarca de Anamã - Registros Públicos || 56201",
    "Vara Única da Comarca de Anori - Criminal || 30801",
    "Vara Única da Comarca de Anori - Cível || 30901",
    "Vara Única da Comarca de Anori - Execução Penal || 37001",
    "Vara Única da Comarca de Anori - Família || 31001",
    "Vara Única da Comarca de Anori - Infância e Juventude Cível || 31101",
    "Vara Única da Comarca de Anori - Infância e Juventude Infracional || 31201",
    "Vara Única da Comarca de Anori - JE Criminal || 31301",
    "Vara Única da Comarca de Anori - JE Cível || 31401",
    "Vara Única da Comarca de Anori - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 76701",
    "Vara Única da Comarca de Anori - Registros Públicos || 56001",
    "Vara Única da Comarca de Apuí - Criminal || 34501",
    "Vara Única da Comarca de Apuí - Cível || 34601",
    "Vara Única da Comarca de Apuí - Execução Penal || 37201",
    "Vara Única da Comarca de Apuí - Família || 34701",
    "Vara Única da Comarca de Apuí - Infância e Juventude Cível || 34801",
    "Vara Única da Comarca de Apuí - Infância e Juventude Infracional || 34901",
    "Vara Única da Comarca de Apuí - JE Criminal || 35001",
    "Vara Única da Comarca de Apuí - JE Cível || 35101",
    "Vara Única da Comarca de Apuí - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 76401",
    "Vara Única da Comarca de Apuí - Registros Públicos || 56701",
    "Vara Única da Comarca de Atalaia do Norte - Criminal || 18601",
    "Vara Única da Comarca de Atalaia do Norte - Cível || 18701",
    "Vara Única da Comarca de Atalaia do Norte - Execução Penal || 37601",
    "Vara Única da Comarca de Atalaia do Norte - Família || 18801",
    "Vara Única da Comarca de Atalaia do Norte - Infância e Juventude Cível || 19001",
    "Vara Única da Comarca de Atalaia do Norte - Infância e Juventude Infracional || 19201",
    "Vara Única da Comarca de Atalaia do Norte - JE Criminal || 19301",
    "Vara Única da Comarca de Atalaia do Norte - JE Cível || 19501",
    "Vara Única da Comarca de Atalaia do Norte - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 78401",
    "Vara Única da Comarca de Atalaia do Norte - Registros Públicos || 58001",
    "Vara Única da Comarca de Autazes - Criminal || 7701",
    "Vara Única da Comarca de Autazes - Cível || 7801",
    "Vara Única da Comarca de Autazes - Execução Penal || 37401",
    "Vara Única da Comarca de Autazes - Família || 7901",
    "Vara Única da Comarca de Autazes - Infância e Juventude Cível || 8001",
    "Vara Única da Comarca de Autazes - Infância e Juventude Infracional || 8101",
    "Vara Única da Comarca de Autazes - JE Criminal || 8201",
    "Vara Única da Comarca de Autazes - JE Cível || 8301",
    "Vara Única da Comarca de Autazes - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 81301",
    "Vara Única da Comarca de Autazes - Registros Públicos || 54401",
    "Vara Única da Comarca de Barcelos - Criminal || 11901",
    "Vara Única da Comarca de Barcelos - Cível || 12001",
    "Vara Única da Comarca de Barcelos - Execução Penal || 38001",
    "Vara Única da Comarca de Barcelos - Família || 12101",
    "Vara Única da Comarca de Barcelos - Infância e Juventude Cível || 12201",
    "Vara Única da Comarca de Barcelos - Infância e Juventude Infracional || 12301",
    "Vara Única da Comarca de Barcelos - JE Criminal || 12401",
    "Vara Única da Comarca de Barcelos - JE Cível || 12501",
    "Vara Única da Comarca de Barcelos - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 78201",
    "Vara Única da Comarca de Barcelos - Registros Públicos || 54801",
    "Vara Única da Comarca de Barreirinha - Criminal || 42",
    "Vara Única da Comarca de Barreirinha - Cível || 142",
    "Vara Única da Comarca de Barreirinha - Execução Penal || 38401",
    "Vara Única da Comarca de Barreirinha - Família || 242",
    "Vara Única da Comarca de Barreirinha - Infância e Juventude Cível || 342",
    "Vara Única da Comarca de Barreirinha - Infância e Juventude Infracional || 442",
    "Vara Única da Comarca de Barreirinha - JE Criminal || 542",
    "Vara Única da Comarca de Barreirinha - JE Cível || 642",
    "Vara Única da Comarca de Barreirinha - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 81401",
    "Vara Única da Comarca de Barreirinha - Registros Públicos || 56901",
    "Vara Única da Comarca de Benjamin Constant - Criminal || 17901",
    "Vara Única da Comarca de Benjamin Constant - Cível || 18001",
    "Vara Única da Comarca de Benjamin Constant - Execução Penal || 38601",
    "Vara Única da Comarca de Benjamin Constant - Família || 18101",
    "Vara Única da Comarca de Benjamin Constant - Infância e Juventude Cível || 18201",
    "Vara Única da Comarca de Benjamin Constant - Infância e Juventude Infracional || 18301",
    "Vara Única da Comarca de Benjamin Constant - JE Criminal || 18401",
    "Vara Única da Comarca de Benjamin Constant - JE Cível || 18501",
    "Vara Única da Comarca de Benjamin Constant - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 81701",
    "Vara Única da Comarca de Benjamin Constant - Registros Públicos || 55701",
    "Vara Única da Comarca de Beruri - Criminal || 14701",
    "Vara Única da Comarca de Beruri - Cível || 14801",
    "Vara Única da Comarca de Beruri - Execução Penal || 38901",
    "Vara Única da Comarca de Beruri - Família || 14901",
    "Vara Única da Comarca de Beruri - Infância e Juventude Cível || 15001",
    "Vara Única da Comarca de Beruri - Infância e Juventude Infracional || 15101",
    "Vara Única da Comarca de Beruri - JE Criminal || 15201",
    "Vara Única da Comarca de Beruri - JE Cível || 15301",
    "Vara Única da Comarca de Beruri - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 80601",
    "Vara Única da Comarca de Beruri - Registros Públicos || 54901",
    "Vara Única da Comarca de Boa Vista do Ramos - Criminal || 43",
    "Vara Única da Comarca de Boa Vista do Ramos - Cível || 143",
    "Vara Única da Comarca de Boa Vista do Ramos - Execução Penal || 39801",
    "Vara Única da Comarca de Boa Vista do Ramos - Família || 243",
    "Vara Única da Comarca de Boa Vista do Ramos - Infância e Juventude Cível || 343",
    "Vara Única da Comarca de Boa Vista do Ramos - Infância e Juventude Infracional || 443",
    "Vara Única da Comarca de Boa Vista do Ramos - JE Criminal || 543",
    "Vara Única da Comarca de Boa Vista do Ramos - JE Cível || 643",
    "Vara Única da Comarca de Boa Vista do Ramos - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 80901",
    "Vara Única da Comarca de Boa Vista do Ramos - Registros Públicos || 57001",
    "Vara Única da Comarca de Boca do Acre - Criminal || 35901",
    "Vara Única da Comarca de Boca do Acre - Cível || 36001",
    "Vara Única da Comarca de Boca do Acre - Execução Penal || 40001",
    "Vara Única da Comarca de Boca do Acre - Família || 36101",
    "Vara Única da Comarca de Boca do Acre - Infância e Juventude Cível || 36201",
    "Vara Única da Comarca de Boca do Acre - Infância e Juventude Infracional || 36301",
    "Vara Única da Comarca de Boca do Acre - JE Criminal || 36401",
    "Vara Única da Comarca de Boca do Acre - JE Cível || 36501",
    "Vara Única da Comarca de Boca do Acre - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 81901",
    "Vara Única da Comarca de Boca do Acre - Registros Públicos || 57101",
    "Vara Única da Comarca de Borba - Criminal || 54",
    "Vara Única da Comarca de Borba - Cível || 154",
    "Vara Única da Comarca de Borba - Execução Penal || 48501",
    "Vara Única da Comarca de Borba - Família || 254",
    "Vara Única da Comarca de Borba - Infância e Juventude Cível || 354",
    "Vara Única da Comarca de Borba - Infância e Juventude Infracional || 454",
    "Vara Única da Comarca de Borba - JE Criminal || 554",
    "Vara Única da Comarca de Borba - JE Cível || 654",
    "Vara Única da Comarca de Borba - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 77701",
    "Vara Única da Comarca de Borba - Registros Públicos || 57401",
    "Vara Única da Comarca de Caapiranga - Criminal || 35201",
    "Vara Única da Comarca de Caapiranga - Cível || 35301",
    "Vara Única da Comarca de Caapiranga - Execução Penal || 48101",
    "Vara Única da Comarca de Caapiranga - Família || 35401",
    "Vara Única da Comarca de Caapiranga - Infância e Juventude Cível || 35501",
    "Vara Única da Comarca de Caapiranga - Infância e Juventude Infracional || 35601",
    "Vara Única da Comarca de Caapiranga - JE Criminal || 35701",
    "Vara Única da Comarca de Caapiranga - JE Cível || 35801",
    "Vara Única da Comarca de Caapiranga - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 80101",
    "Vara Única da Comarca de Caapiranga - Registros Públicos || 56801",
    "Vara Única da Comarca de Canutama - Criminal || 45",
    "Vara Única da Comarca de Canutama - Cível || 145",
    "Vara Única da Comarca de Canutama - Execução Penal || 47701",
    "Vara Única da Comarca de Canutama - Família || 245",
    "Vara Única da Comarca de Canutama - Infância e Juventude Cível || 345",
    "Vara Única da Comarca de Canutama - Infância e Juventude Infracional || 445",
    "Vara Única da Comarca de Canutama - JE Criminal || 545",
    "Vara Única da Comarca de Canutama - JE Cível || 645",
    "Vara Única da Comarca de Canutama - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 77901",
    "Vara Única da Comarca de Canutama - Registros Públicos || 56501",
    "Vara Única da Comarca de Carauari - Criminal || 12601",
    "Vara Única da Comarca de Carauari - Cível || 12701",
    "Vara Única da Comarca de Carauari - Execução Penal || 47501",
    "Vara Única da Comarca de Carauari - Família || 12801",
    "Vara Única da Comarca de Carauari - Infância e Juventude Cível || 12901",
    "Vara Única da Comarca de Carauari - Infância e Juventude Infracional || 13001",
    "Vara Única da Comarca de Carauari - JE Criminal || 13101",
    "Vara Única da Comarca de Carauari - JE Cível || 13201",
    "Vara Única da Comarca de Carauari - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 78501",
    "Vara Única da Comarca de Carauari - Registros Públicos || 55101",
    "Vara Única da Comarca de Careiro Castanho - Criminal || 6301",
    "Vara Única da Comarca de Careiro Castanho - Cível || 6401",
    "Vara Única da Comarca de Careiro Castanho - Execução Penal || 47301",
    "Vara Única da Comarca de Careiro Castanho - Família || 6501",
    "Vara Única da Comarca de Careiro Castanho - Infância e Juventude Cível || 6601",
    "Vara Única da Comarca de Careiro Castanho - Infância e Juventude Infracional || 6701",
    "Vara Única da Comarca de Careiro Castanho - JE Criminal || 6801",
    "Vara Única da Comarca de Careiro Castanho - JE Cível || 6901",
    "Vara Única da Comarca de Careiro Castanho - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 76801",
    "Vara Única da Comarca de Careiro Castanho - Registros Públicos || 54301",
    "Vara Única da Comarca de Careiro da Várzea - Criminal || 7001",
    "Vara Única da Comarca de Careiro da Várzea - Cível || 7101",
    "Vara Única da Comarca de Careiro da Várzea - Execução Penal || 47101",
    "Vara Única da Comarca de Careiro da Várzea - Família || 7201",
    "Vara Única da Comarca de Careiro da Várzea - Infância e Juventude Cível || 7301",
    "Vara Única da Comarca de Careiro da Várzea - Infância e Juventude Infracional || 7401",
    "Vara Única da Comarca de Careiro da Várzea - JE Criminal || 7501",
    "Vara Única da Comarca de Careiro da Várzea - JE Cível || 7601",
    "Vara Única da Comarca de Careiro da Várzea - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 78601",
    "Vara Única da Comarca de Careiro da Várzea - Registros Públicos || 54501",
    "Vara Única da Comarca de Codajás - Criminal || 60",
    "Vara Única da Comarca de Codajás - Cível || 160",
    "Vara Única da Comarca de Codajás - Execução Penal || 46901",
    "Vara Única da Comarca de Codajás - Família || 260",
    "Vara Única da Comarca de Codajás - Infância e Juventude Cível || 360",
    "Vara Única da Comarca de Codajás - Infância e Juventude Infracional || 460",
    "Vara Única da Comarca de Codajás - JE Criminal || 560",
    "Vara Única da Comarca de Codajás - JE Cível || 660",
    "Vara Única da Comarca de Codajás - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 80501",
    "Vara Única da Comarca de Codajás - Registros Públicos || 57501",
    "Vara Única da Comarca de Eirunepé - Criminal || 11201",
    "Vara Única da Comarca de Eirunepé - Cível || 11301",
    "Vara Única da Comarca de Eirunepé - Execução Penal || 46701",
    "Vara Única da Comarca de Eirunepé - Família || 11401",
    "Vara Única da Comarca de Eirunepé - Infância e Juventude Cível || 11501",
    "Vara Única da Comarca de Eirunepé - Infância e Juventude Infracional || 11601",
    "Vara Única da Comarca de Eirunepé - JE Criminal || 11701",
    "Vara Única da Comarca de Eirunepé - JE Cível || 11801",
    "Vara Única da Comarca de Eirunepé - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 82601",
    "Vara Única da Comarca de Eirunepé - Registros Públicos || 54701",
    "Vara Única da Comarca de Envira - Criminal || 4201",
    "Vara Única da Comarca de Envira - Cível || 4301",
    "Vara Única da Comarca de Envira - Execução Penal || 46501",
    "Vara Única da Comarca de Envira - Família || 4401",
    "Vara Única da Comarca de Envira - Infância e Juventude Cível || 4501",
    "Vara Única da Comarca de Envira - Infância e Juventude Infracional || 4601",
    "Vara Única da Comarca de Envira - JE Criminal || 4701",
    "Vara Única da Comarca de Envira - JE Cível || 4801",
    "Vara Única da Comarca de Envira - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 78701",
    "Vara Única da Comarca de Envira - Registros Públicos || 54001",
    "Vara Única da Comarca de Envira - xxx || 3401",
    "Vara Única da Comarca de Fonte Boa - Criminal || 25201",
    "Vara Única da Comarca de Fonte Boa - Cível || 25301",
    "Vara Única da Comarca de Fonte Boa - Execução Penal || 44701",
    "Vara Única da Comarca de Fonte Boa - Família || 25401",
    "Vara Única da Comarca de Fonte Boa - Infância e Juventude Cível || 25501",
    "Vara Única da Comarca de Fonte Boa - Infância e Juventude Infracional || 25601",
    "Vara Única da Comarca de Fonte Boa - JE Criminal || 25701",
    "Vara Única da Comarca de Fonte Boa - JE Cível || 25801",
    "Vara Única da Comarca de Fonte Boa - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 80401",
    "Vara Única da Comarca de Fonte Boa - Registros Públicos || 57801",
    "Vara Única da Comarca de Guajará - Criminal || 101",
    "Vara Única da Comarca de Guajará - Cível || 201",
    "Vara Única da Comarca de Guajará - Execução Penal || 44401",
    "Vara Única da Comarca de Guajará - Família || 301",
    "Vara Única da Comarca de Guajará - Infância e Juventude Cível || 401",
    "Vara Única da Comarca de Guajará - Infância e Juventude Infracional || 501",
    "Vara Única da Comarca de Guajará - JE Criminal || 601",
    "Vara Única da Comarca de Guajará - JE Cível || 701",
    "Vara Única da Comarca de Guajará - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 76001",
    "Vara Única da Comarca de Guajará - Registros Públicos || 53801",
    "Vara Única da Comarca de Ipixuna - Criminal || 28901",
    "Vara Única da Comarca de Ipixuna - Cível || 29101",
    "Vara Única da Comarca de Ipixuna - Execução Penal || 44101",
    "Vara Única da Comarca de Ipixuna - Família || 29301",
    "Vara Única da Comarca de Ipixuna - Infância e Juventude Cível || 29701",
    "Vara Única da Comarca de Ipixuna - Infância e Juventude Infracional || 29801",
    "Vara Única da Comarca de Ipixuna - JE Criminal || 29901",
    "Vara Única da Comarca de Ipixuna - JE Cível || 30001",
    "Vara Única da Comarca de Ipixuna - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 80301",
    "Vara Única da Comarca de Ipixuna - Registros Públicos || 55901",
    "Vara Única da Comarca de Itamarati - Criminal || 28701",
    "Vara Única da Comarca de Itamarati - Cível || 28801",
    "Vara Única da Comarca de Itamarati - Execução Penal || 43901",
    "Vara Única da Comarca de Itamarati - Família || 29001",
    "Vara Única da Comarca de Itamarati - Infância e Juventude Cível || 29201",
    "Vara Única da Comarca de Itamarati - Infância e Juventude Infracional || 29401",
    "Vara Única da Comarca de Itamarati - JE Criminal || 29501",
    "Vara Única da Comarca de Itamarati - JE Cível || 29601",
    "Vara Única da Comarca de Itamarati - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 76101",
    "Vara Única da Comarca de Itamarati - Registros Públicos || 55801",
    "Vara Única da Comarca de Itapiranga - Criminal || 56",
    "Vara Única da Comarca de Itapiranga - Cível || 156",
    "Vara Única da Comarca de Itapiranga - Execução Penal || 43701",
    "Vara Única da Comarca de Itapiranga - Família || 256",
    "Vara Única da Comarca de Itapiranga - Infância e Juventude Cível || 356",
    "Vara Única da Comarca de Itapiranga - Infância e Juventude Infracional || 456",
    "Vara Única da Comarca de Itapiranga - JE Criminal || 556",
    "Vara Única da Comarca de Itapiranga - JE Cível || 656",
    "Vara Única da Comarca de Itapiranga - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 82501",
    "Vara Única da Comarca de Itapiranga - Registros Públicos || 57201",
    "Vara Única da Comarca de Japurá - Criminal || 24501",
    "Vara Única da Comarca de Japurá - Cível || 24601",
    "Vara Única da Comarca de Japurá - Execução Penal || 43501",
    "Vara Única da Comarca de Japurá - Família || 24701",
    "Vara Única da Comarca de Japurá - Infância e Juventude Cível || 24801",
    "Vara Única da Comarca de Japurá - Infância e Juventude Infracional || 24901",
    "Vara Única da Comarca de Japurá - JE Criminal || 25001",
    "Vara Única da Comarca de Japurá - JE Cível || 25101",
    "Vara Única da Comarca de Japurá - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 80001",
    "Vara Única da Comarca de Japurá - Registros Públicos || 55201",
    "Vara Única da Comarca de Juruá - Criminal || 59",
    "Vara Única da Comarca de Juruá - Cível || 159",
    "Vara Única da Comarca de Juruá - Execução Penal || 43301",
    "Vara Única da Comarca de Juruá - Família || 259",
    "Vara Única da Comarca de Juruá - Infância e Juventude Cível || 359",
    "Vara Única da Comarca de Juruá - Infância e Juventude Infracional || 459",
    "Vara Única da Comarca de Juruá - JE Criminal || 559",
    "Vara Única da Comarca de Juruá - JE Cível || 659",
    "Vara Única da Comarca de Juruá - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 78901",
    "Vara Única da Comarca de Juruá - Registros Públicos || 53601",
    "Vara Única da Comarca de Jutaí - Criminal || 25901",
    "Vara Única da Comarca de Jutaí - Cível || 26001",
    "Vara Única da Comarca de Jutaí - Execução Penal || 43101",
    "Vara Única da Comarca de Jutaí - Família || 26101",
    "Vara Única da Comarca de Jutaí - Infância e Juventude Cível || 26301",
    "Vara Única da Comarca de Jutaí - Infância e Juventude Infracional || 26201",
    "Vara Única da Comarca de Jutaí - JE Criminal || 26401",
    "Vara Única da Comarca de Jutaí - JE Cível || 26501",
    "Vara Única da Comarca de Jutaí - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 79101",
    "Vara Única da Comarca de Jutaí - Registros Públicos || 55401",
    "Vara Única da Comarca de Lábrea - Criminal || 22101",
    "Vara Única da Comarca de Lábrea - Cível || 22201",
    "Vara Única da Comarca de Lábrea - Execução Penal || 42901",
    "Vara Única da Comarca de Lábrea - Família || 22301",
    "Vara Única da Comarca de Lábrea - Infância e Juventude Cível || 22401",
    "Vara Única da Comarca de Lábrea - Infância e Juventude Infracional || 22501",
    "Vara Única da Comarca de Lábrea - JE Criminal || 22601",
    "Vara Única da Comarca de Lábrea - JE Cível || 22701",
    "Vara Única da Comarca de Lábrea - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 79201",
    "Vara Única da Comarca de Lábrea - Registros Públicos || 58201",
    "Vara Única da Comarca de Manaquiri - Criminal || 801",
    "Vara Única da Comarca de Manaquiri - Cível || 901",
    "Vara Única da Comarca de Manaquiri - Execução Penal || 42701",
    "Vara Única da Comarca de Manaquiri - Família || 1001",
    "Vara Única da Comarca de Manaquiri - Infância e Juventude Cível || 1101",
    "Vara Única da Comarca de Manaquiri - Infância e Juventude Infracional || 1201",
    "Vara Única da Comarca de Manaquiri - JE Criminal || 1301",
    "Vara Única da Comarca de Manaquiri - JE Cível || 1401",
    "Vara Única da Comarca de Manaquiri - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 78101",
    "Vara Única da Comarca de Manaquiri - Registros Públicos || 53701",
    "Vara Única da Comarca de Maraã - Criminal || 28001",
    "Vara Única da Comarca de Maraã - Cível || 28101",
    "Vara Única da Comarca de Maraã - Execução Penal || 42501",
    "Vara Única da Comarca de Maraã - Família || 28201",
    "Vara Única da Comarca de Maraã - Infância e Juventude Cível || 28301",
    "Vara Única da Comarca de Maraã - Infância e Juventude Infracional || 28601",
    "Vara Única da Comarca de Maraã - JE Criminal || 28401",
    "Vara Única da Comarca de Maraã - JE Cível || 28501",
    "Vara Única da Comarca de Maraã - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 77101",
    "Vara Única da Comarca de Maraã - Registros Públicos || 55501",
    "Vara Única da Comarca de Nhamundá - Criminal || 300",
    "Vara Única da Comarca de Nhamundá - Cível || 400",
    "Vara Única da Comarca de Nhamundá - Execução Penal || 42301",
    "Vara Única da Comarca de Nhamundá - Família || 500",
    "Vara Única da Comarca de Nhamundá - Infância e Juventude Cível || 600",
    "Vara Única da Comarca de Nhamundá - Infância e Juventude Infracional || 700",
    "Vara Única da Comarca de Nhamundá - JE Criminal || 800",
    "Vara Única da Comarca de Nhamundá - JE Cível || 900",
    "Vara Única da Comarca de Nhamundá - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 77501",
    "Vara Única da Comarca de Nhamundá - Registros Públicos || 58301",
    "Vara Única da Comarca de Nova Olinda do Norte - Criminal || 32201",
    "Vara Única da Comarca de Nova Olinda do Norte - Cível || 32301",
    "Vara Única da Comarca de Nova Olinda do Norte - Execução Penal || 42101",
    "Vara Única da Comarca de Nova Olinda do Norte - Família || 32401",
    "Vara Única da Comarca de Nova Olinda do Norte - Infância e Juventude Cível || 32501",
    "Vara Única da Comarca de Nova Olinda do Norte - Infância e Juventude Infracional || 32601",
    "Vara Única da Comarca de Nova Olinda do Norte - JE Criminal || 32701",
    "Vara Única da Comarca de Nova Olinda do Norte - JE Cível || 32801",
    "Vara Única da Comarca de Nova Olinda do Norte - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 81601",
    "Vara Única da Comarca de Nova Olinda do Norte - Registros Públicos || 56301",
    "Vara Única da Comarca de Novo Airão - Criminal || 3601",
    "Vara Única da Comarca de Novo Airão - Cível || 3501",
    "Vara Única da Comarca de Novo Airão - Execução Penal || 41901",
    "Vara Única da Comarca de Novo Airão - Família || 3701",
    "Vara Única da Comarca de Novo Airão - Infância e Juventude Cível || 3801",
    "Vara Única da Comarca de Novo Airão - Infância e Juventude Infracional || 3901",
    "Vara Única da Comarca de Novo Airão - JE Criminal || 4001",
    "Vara Única da Comarca de Novo Airão - JE Cível || 4101",
    "Vara Única da Comarca de Novo Airão - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 82201",
    "Vara Única da Comarca de Novo Airão - Registros Públicos || 54101",
    "Vara Única da Comarca de Novo Aripuanã - Criminal || 244",
    "Vara Única da Comarca de Novo Aripuanã - Cível || 344",
    "Vara Única da Comarca de Novo Aripuanã - Execução Penal || 41601",
    "Vara Única da Comarca de Novo Aripuanã - Família || 444",
    "Vara Única da Comarca de Novo Aripuanã - Infância e Juventude Cível || 544",
    "Vara Única da Comarca de Novo Aripuanã - Infância e Juventude Infracional || 644",
    "Vara Única da Comarca de Novo Aripuanã - JE Criminal || 44",
    "Vara Única da Comarca de Novo Aripuanã - JE Cível || 144",
    "Vara Única da Comarca de Novo Aripuanã - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 75801",
    "Vara Única da Comarca de Novo Aripuanã - Registros Públicos || 57701",
    "Vara Única da Comarca de Pauini - Criminal || 250",
    "Vara Única da Comarca de Pauini - Cível || 350",
    "Vara Única da Comarca de Pauini - Execução Penal || 41701",
    "Vara Única da Comarca de Pauini - Família || 450",
    "Vara Única da Comarca de Pauini - Infância e Juventude Cível || 650",
    "Vara Única da Comarca de Pauini - Infância e Juventude Infracional || 550",
    "Vara Única da Comarca de Pauini - JE Criminal || 50",
    "Vara Única da Comarca de Pauini - JE Cível || 150",
    "Vara Única da Comarca de Pauini - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 82701",
    "Vara Única da Comarca de Pauini - Registros Públicos || 57301",
    "Vara Única da Comarca de Presidente Figueiredo - Criminal || 2",
    "Vara Única da Comarca de Presidente Figueiredo - Cível || 1",
    "Vara Única da Comarca de Presidente Figueiredo - Execução Penal || 41301",
    "Vara Única da Comarca de Presidente Figueiredo - Família || 5",
    "Vara Única da Comarca de Presidente Figueiredo - Infância e Juventude Cível || 6",
    "Vara Única da Comarca de Presidente Figueiredo - Infância e Juventude Infracional || 7",
    "Vara Única da Comarca de Presidente Figueiredo - JE Criminal || 4",
    "Vara Única da Comarca de Presidente Figueiredo - JE Cível || 3",
    "Vara Única da Comarca de Presidente Figueiredo - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 81201",
    "Vara Única da Comarca de Presidente Figueiredo - Registros Públicos || 53901",
    "Vara Única da Comarca de Rio Preto da Eva - Criminal || 9101",
    "Vara Única da Comarca de Rio Preto da Eva - Cível || 9201",
    "Vara Única da Comarca de Rio Preto da Eva - Execução Penal || 41101",
    "Vara Única da Comarca de Rio Preto da Eva - Família || 9301",
    "Vara Única da Comarca de Rio Preto da Eva - Infância e Juventude Cível || 9401",
    "Vara Única da Comarca de Rio Preto da Eva - Infância e Juventude Infracional || 9501",
    "Vara Única da Comarca de Rio Preto da Eva - JE Criminal || 9601",
    "Vara Única da Comarca de Rio Preto da Eva - JE Cível || 9701",
    "Vara Única da Comarca de Rio Preto da Eva - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 80801",
    "Vara Única da Comarca de Rio Preto da Eva - Registros Públicos || 55001",
    "Vara Única da Comarca de Santa Isabel do Rio Negro - Criminal || 232",
    "Vara Única da Comarca de Santa Isabel do Rio Negro - Cível || 332",
    "Vara Única da Comarca de Santa Isabel do Rio Negro - Execução Penal || 40901",
    "Vara Única da Comarca de Santa Isabel do Rio Negro - Família || 432",
    "Vara Única da Comarca de Santa Isabel do Rio Negro - Infância e Juventude Cível || 532",
    "Vara Única da Comarca de Santa Isabel do Rio Negro - Infância e Juventude Infracional || 632",
    "Vara Única da Comarca de Santa Isabel do Rio Negro - JE Criminal || 732",
    "Vara Única da Comarca de Santa Isabel do Rio Negro - JE Cível || 832",
    "Vara Única da Comarca de Santa Isabel do Rio Negro - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 79701",
    "Vara Única da Comarca de Santa Isabel do Rio Negro - Registros Públicos || 55601",
    "Vara Única da Comarca de Santo Antônio do Içá - Criminal || 27301",
    "Vara Única da Comarca de Santo Antônio do Içá - Cível || 27401",
    "Vara Única da Comarca de Santo Antônio do Içá - Execução Penal || 40701",
    "Vara Única da Comarca de Santo Antônio do Içá - Família || 27501",
    "Vara Única da Comarca de Santo Antônio do Içá - Infância e Juventude Cível || 27601",
    "Vara Única da Comarca de Santo Antônio do Içá - Infância e Juventude Infracional || 27701",
    "Vara Única da Comarca de Santo Antônio do Içá - JE Criminal || 27801",
    "Vara Única da Comarca de Santo Antônio do Içá - JE Cível || 27901",
    "Vara Única da Comarca de Santo Antônio do Içá - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 82001",
    "Vara Única da Comarca de Santo Antônio do Içá - Registros Públicos || 55301",
    "Vara Única da Comarca de Silves - Criminal || 8401",
    "Vara Única da Comarca de Silves - Cível || 8501",
    "Vara Única da Comarca de Silves - Execução Penal || 39501",
    "Vara Única da Comarca de Silves - Família || 8601",
    "Vara Única da Comarca de Silves - Infância e Juventude Cível || 8701",
    "Vara Única da Comarca de Silves - Infância e Juventude Infracional || 8801",
    "Vara Única da Comarca de Silves - JE Criminal || 8901",
    "Vara Única da Comarca de Silves - JE Cível || 9001",
    "Vara Única da Comarca de Silves - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 81001",
    "Vara Única da Comarca de Silves - Registros Públicos || 54601",
    "Vara Única da Comarca de São Gabriel da Cachoeira - Criminal || 26601",
    "Vara Única da Comarca de São Gabriel da Cachoeira - Cível || 26701",
    "Vara Única da Comarca de São Gabriel da Cachoeira - Execução Penal || 40501",
    "Vara Única da Comarca de São Gabriel da Cachoeira - Família || 26801",
    "Vara Única da Comarca de São Gabriel da Cachoeira - Infância e Juventude Cível || 26901",
    "Vara Única da Comarca de São Gabriel da Cachoeira - Infância e Juventude Infracional || 27001",
    "Vara Única da Comarca de São Gabriel da Cachoeira - JE Criminal || 27101",
    "Vara Única da Comarca de São Gabriel da Cachoeira - JE Cível || 27201",
    "Vara Única da Comarca de São Gabriel da Cachoeira - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 77201",
    "Vara Única da Comarca de São Gabriel da Cachoeira - Registros Públicos || 58501",
    "Vara Única da Comarca de São Paulo de Olivença - Criminal || 30101",
    "Vara Única da Comarca de São Paulo de Olivença - Cível || 30201",
    "Vara Única da Comarca de São Paulo de Olivença - Execução Penal || 40301",
    "Vara Única da Comarca de São Paulo de Olivença - Família || 30301",
    "Vara Única da Comarca de São Paulo de Olivença - Infância e Juventude Cível || 30401",
    "Vara Única da Comarca de São Paulo de Olivença - Infância e Juventude Infracional || 30501",
    "Vara Única da Comarca de São Paulo de Olivença - JE Criminal || 30601",
    "Vara Única da Comarca de São Paulo de Olivença - JE Cível || 30701",
    "Vara Única da Comarca de São Paulo de Olivença - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 79501",
    "Vara Única da Comarca de São Paulo de Olivença - Registros Públicos || 56101",
    "Vara Única da Comarca de São Sebastião do Uatumã - Criminal || 55",
    "Vara Única da Comarca de São Sebastião do Uatumã - Cível || 155",
    "Vara Única da Comarca de São Sebastião do Uatumã - Execução Penal || 39701",
    "Vara Única da Comarca de São Sebastião do Uatumã - Família || 255",
    "Vara Única da Comarca de São Sebastião do Uatumã - Infância e Juventude Cível || 355",
    "Vara Única da Comarca de São Sebastião do Uatumã - Infância e Juventude Infracional || 455",
    "Vara Única da Comarca de São Sebastião do Uatumã - JE Criminal || 555",
    "Vara Única da Comarca de São Sebastião do Uatumã - JE Cível || 655",
    "Vara Única da Comarca de São Sebastião do Uatumã - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 79601",
    "Vara Única da Comarca de São Sebastião do Uatumã - Registros Públicos || 56601",
    "Vara Única da Comarca de Tapauá - Criminal || 53",
    "Vara Única da Comarca de Tapauá - Cível || 153",
    "Vara Única da Comarca de Tapauá - Execução Penal || 39301",
    "Vara Única da Comarca de Tapauá - Família || 253",
    "Vara Única da Comarca de Tapauá - Infância e Juventude Cível || 353",
    "Vara Única da Comarca de Tapauá - Infância e Juventude Infracional || 453",
    "Vara Única da Comarca de Tapauá - JE Criminal || 553",
    "Vara Única da Comarca de Tapauá - JE Cível || 653",
    "Vara Única da Comarca de Tapauá - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 79801",
    "Vara Única da Comarca de Tapauá - Registros Públicos || 57601",
    "Vara Única da Comarca de Uarini - Criminal || 18901",
    "Vara Única da Comarca de Uarini - Cível || 19101",
    "Vara Única da Comarca de Uarini - Execução Penal || 38801",
    "Vara Única da Comarca de Uarini - Família || 19401",
    "Vara Única da Comarca de Uarini - Infância e Juventude Cível || 19601",
    "Vara Única da Comarca de Uarini - Infância e Juventude Infracional || 19701",
    "Vara Única da Comarca de Uarini - JE Criminal || 19801",
    "Vara Única da Comarca de Uarini - JE Cível || 19901",
    "Vara Única da Comarca de Uarini - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 77301",
    "Vara Única da Comarca de Uarini - Registros Públicos || 58101",
    "Vara Única da Comarca de Urucará - Criminal || 49",
    "Vara Única da Comarca de Urucará - Cível || 149",
    "Vara Única da Comarca de Urucará - Execução Penal || 38201",
    "Vara Única da Comarca de Urucará - Família || 249",
    "Vara Única da Comarca de Urucará - Infância e Juventude Cível || 349",
    "Vara Única da Comarca de Urucará - Infância e Juventude Infracional || 449",
    "Vara Única da Comarca de Urucará - JE Criminal || 549",
    "Vara Única da Comarca de Urucará - JE Cível || 649",
    "Vara Única da Comarca de Urucará - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 80701",
    "Vara Única da Comarca de Urucará - Registros Públicos || 56401",
    "Vara Única da Comarca de Urucurituba - Criminal || 21401",
    "Vara Única da Comarca de Urucurituba - Cível || 21501",
    "Vara Única da Comarca de Urucurituba - Execução Penal || 37701",
    "Vara Única da Comarca de Urucurituba - Família || 21601",
    "Vara Única da Comarca de Urucurituba - Infância e Juventude Cível || 21701",
    "Vara Única da Comarca de Urucurituba - Infância e Juventude Infracional || 21801",
    "Vara Única da Comarca de Urucurituba - JE Criminal || 21901",
    "Vara Única da Comarca de Urucurituba - JE Cível || 22001",
    "Vara Única da Comarca de Urucurituba - Juizado Especializado da Violê;ncia Doméstica (Maria da Penha) || 81501",
    "Vara Única da Comarca de Urucurituba - Registros Públicos || 58401",
    "Vara Única da Comarca de xxxx - Criminal || 33701",
    "Vara Única da Comarca de xxxx - Cível || 33801",
    "Vara Única da Comarca de xxxx - Família || 33901",
    "Vara Única da Comarca de xxxx - Infância e Juventude Cível || 34001",
    "Vara Única da Comarca de xxxx - Infância e Juventude Infracional || 34101",
    "Vara Única da Comarca de xxxx - JE Criminal || 34201",
    "Vara Única da Comarca de xxxx - JE Cível || 34301"
]